### ISSUE TITLE
there is an error running train.py 

### ISSUE THREAD

**Issue by liangzimei** [hosang/gossipnet#2]
Traceback (most recent call last):                                                                                                                                                              
  File "train.py", line 17, in <module>                                                                                                                                                                
    import imdb                                                                                                                                                                                                 
  File "/home/zhangyb/DL/Detection/gossipnet/imdb/__init__.py", line 13, in <module>                                                                                                                            
    from imdb.pal import load_pal                                                                                                                                                                             
  File "/home/zhangyb/DL/Detection/gossipnet/imdb/pal.py", line 11, in <module>                                                                                                                                  
    from imdb.file_formats import pal                                                                                                                                                                   
  File "/home/zhangyb/DL/Detection/gossipnet/imdb/file_formats/pal.py", line 5, in <module>                                                                                                      
    from . import AnnoList_pb2                                                                                                                                                                      
ImportError: cannot import name AnnoList_pb2

do you have any suggestions? thanks in advance....

**Comment by hosang** [comment]
Did you run make?

**Comment by liangzimei** [comment]
haha, i ignore it, thank you... @hosang
